### PR TITLE
Change ``connection`` close logic to fix some potential probelms.

### LINKED ISSUE #579: Flaky-test: [SimpleIntegrationTest].[testSubscribeRejectionWithSameClientId]
[SimpleIntegrationTest] is flaky. The [testSubscribeRejectionWithSameClientId] test method fails sporadically.

[example failure](https://github.com/streamnative/mop/runs/5869666283?check_suite_focus=true#logs)

```
Error:  testSubscribeRejectionWithSameClientId(io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.base.SimpleIntegrationTest)  Time elapsed: 0.068 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
```

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
Error:  Tests run: 50, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 44.629 s <<< FAILURE! - in io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.base.SimpleIntegrationTest
Error:  testSubscribeRejectionWithSameClientId(io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.base.SimpleIntegrationTest)  Time elapsed: 0.068 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at io.streamnative.pulsar.handlers.mqtt.mqtt3.fusesource.base.SimpleIntegrationTest.testSubscribeRejectionWithSameClientId(SimpleIntegrationTest.java:289)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

[INFO] 
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by mattisonchao**
Fixes #579 

Master Issue: #579

### Motivation

Based on issue #579, I found we exist a problem.

The `Connection#close` method is called multiple times when the previous connection is overwritten and closed by the `client id`, and some errors are thrown when it triggers a race condition.

### Modifications

- Changed all connection close actions to `channel#close` to trigger `channelInactive`, which then calls `Connection#close` to clean up data.
- Fix issue #579 by stopping connection 1 reconnecting and quickly cleaning up `subscriptionManager` to avoid duplicate subscriptions.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

File: tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java [hunk 1]
```diff
@@ -283,12 +285,13 @@ public void testSubscribeRejectionWithSameClientId() throws Exception {
...
+        mqtt2.setClientId("client-id-0");
         connection2 = mqtt2.blockingConnection();
         connection2.connect();
         Assert.assertTrue(connection2.isConnected());
-        Awaitility.await().untilAsserted(() -> Assert.assertTrue(connection1.isConnected()));
+        Awaitility.await().untilAsserted(() -> Assert.assertFalse(connection1.isConnected()));
         connection2.subscribe(topics);
+        Assert.assertTrue(connection2.isConnected());
         connection2.disconnect();
         connection1.disconnect();
```
Comment (Technoboy-) [inline tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java:296]: Help to check the consumer size in this test.
